[package]
name = "darkhorse-code"
version = "0.1.0"
description = "最好用的IDE，个人使用"
authors = ["醒过来摸鱼"]
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
dirs = "6"
arborium = { version = "2", default-features = false, features = ["lang-python"] }
arborium-theme = "2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
